version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ccommerceApi_image
    networks: ccommerce
    tty: true
    ports:
      - 5000
    links:
      - redis

  redis:
    image: redis:alphine
    image_name: redis
    volumes: ./redisStore:/data
    networks: ccommerce

  networks:
    ccommerce:
      driver: bridge
